[project]
name = "aws-generative-ai-for-developers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "boto3>=1.42.27",
    "jupyter>=1.1.1",
]
